### ISSUE TITLE
conversion issue

### ISSUE THREAD

**Issue by ashwek** [codinia/OpenDS#23]
https://github.com/codinia/OpenDS/blob/77f13b9a4c11c58bdcdccb26cbde8f31e1269847/Sorting/bubbleSort.cpp#L4

since the parameters are of type **pointer**
https://github.com/codinia/OpenDS/blob/77f13b9a4c11c58bdcdccb26cbde8f31e1269847/Sorting/bubbleSort.cpp#L21
we should pass **address** _( **&** arr[j], **&** arr[j+1])_ not values

same issue in heapSort.cpp

**Comment by dhruv-chitkara27** [comment]
solved
